name: Template Sync Initiation

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  template-sync-initiation:
    if: ${{ github.repository == 'paperback-community/template-extensions' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension_repositories:
          [
            paperback-community/general-extensions,
            paperback-community/tracker-extensions,
            paperback-community/madara-extensions,
            paperback-community/webtoon-extensions,
          ]
    steps:
      - name: Dispatch Workflow
        env:
          GH_TOKEN: ${{ secrets.extension_repositories }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ matrix.extension_repositories }}/dispatches \
            -f "event_type=template-sync"
